# dataset basic
dataset: uhcs
img_folder: images
label_folder: labels
n_classes: 2

# train, validation and test split
split_info:
  type: CSVSplit
  test_type: CSVSplit
  split_file: split_cv.csv
  split_col_name: split
  val_split_num: 1
  test_split_num: 0
  train_reverse: True

# data information
train_size: [224, 224]
eval_size: [484, 645]
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

# pixelpick information
max_pixels: 80
n_pixels_per_round: 10
n_init_pixels_per_class: 5
query_strategy: entropy
top_n_percent: 0.05

# data augmentation
augmentations:
  Flip: {p: 0.5}
  ShiftScaleRotate: {shift_limit: 0, scale_limit: [0,1], rotate_limit: 45, p: 0.8}
  RandomBrightnessContrast: {brightness_limit: 0.2, contrast_limit: 0.3, p: 0.8}
  GaussianBlur: { blur_limit: [3,7], p: 0.1 }
  Sharpen: { p: 0.1 }
  GaussNoise: { p: 0.1 }

# training
n_train_iters: 1800
val_interval: 120
print_every_n_val: 1
loss_type: CE
ignore_index: -1
batch_size: 4
optimizer:
  type: AdamW
  encoder_lr: 5.e-5
  decoder_lr: 5.e-4
  weight_decay: 1.e-2

lr_scheduler:
  type: ExponentialLR
  decay_start: 1200
  decay_len: 600
  decay_rate: 0.1
  params: {}

metric: mIoU
